### ISSUE TITLE
Incomplete mainfest.json - Can't currently download the theme from the Community Theme store

### ISSUE THREAD

**Issue by damiankorcz** [Thiews/obsidian-simplicity#1]
The theme throws an 404 error in the console when you try to download it and doesn't download. You are missing the following properties from `manifest.json` which are required. Refer to the official docs for reference: https://docs.obsidian.md/Reference/Manifest.
- `version` is your theme's version.
- `minAppVersion` is the minimum Obsidian app version your current theme version supports *(note that this is the App version not the Installer version).*

Some of the properties you have used there are also not valid (`repo`, `screenshot`, `modes`). Those were only needed for when you submitted the theme. If you ever need to alter them you will have to make a pull request in that repository again. 

Here is an example of a complete `manifest.json` file for your theme:
```json
{
   "name": "Simplicity",
   "version": "1.0.0",
   "minAppVersion": "1.3.0",
   "author": "Thiews",
   "authorUrl": "https://github.com/Thiews",
   "fundingUrl": "https://www.buymeacoffee.com/thiews"
}
```

Also, if you utilise Github's Release feature to version your theme going forward it might be worth maintaining a `versions.json` file. It's handy when you make a release that removes styling from elements that changed in a specific version of Obsidian and you want to make sure that the user that hasn't yet update Obsidian doesn't get the theme update and have something break for them.
More about it here: https://docs.obsidian.md/Reference/Versions
For reference you can see how I use it with my theme: https://github.com/damiankorcz/Prism-Theme/blob/main/versions.json

**Comment by Thiews** [comment]
Thanks for your comment ! I hope it's ok now !

**Comment by damiankorcz** [comment]
Yeah it downloads correctly now!
