### ISSUE TITLE
Amazing theme (question)

### ISSUE THREAD

**Issue by vdruts** [Thiews/obsidian-simplicity#2]
Beautiful theme! Especially with rounded corners. Question, I can't seem to find anyway to change the main 'pink' color style to anything else? I'd love to have some quick options, black/grey, cool tones etc. The pink is a little distracting and hard to read with a pink font.

**Comment by Thiews** [comment]
I don't see what pink color you talk about ! Can you send me a picture ? Have installed the "style setting" plugin to personalize the theme ?

**Comment by vdruts** [comment]
Yes I'm using style-settings.
![image](https://github.com/Thiews/obsidian-simplicity/assets/20264016/a0212026-ae59-4330-8e1e-530d23baf696)

**Comment by Thiews** [comment]
Try to choose a darker pinker color to see if it works better. I made some changes to the theme, normal text should also appear darker

**Comment by vdruts** [comment]
What I mean is, I'd love the ability to change those standard theme/colors without having to manually edit the style-sheet. Right now, I can't seem to find anywhere to do so in the style-settings.

**Comment by vdruts** [comment]
I see the (accent) color changes everything. Ideally there would be a separate option for "text" color... Since it becomes too monotone, and using any accent color that looks nice, the text becomes too light/bright.

**Comment by Thiews** [comment]
I will consider to add an option to change the normal text font color (who should appear very dark). But indeed, I made this choice to have consistency with the overall theme appearance !
